### ISSUE TITLE
PULL_REQUEST_NUMBER not attaching to Task payload definition

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#7892]
Per https://github.com/mozilla-mobile/focus-android/blob/a2eb4e43d87459b65391b0b0a232d8e7bbab21c9/.taskcluster.yml#L217 and https://github.com/mozilla-mobile/focus-android/blob/0c2e0b77fe4fd918672fa55256b881a45d117f3e/taskcluster/focus_android_taskgraph/parameters.py#L32 I should be seeing a `PULL_REQUEST_NUMBER` env-var under `task.payload.env` but am not 🤔 

https://github.com/mozilla-mobile/focus-android/blob/21a3a87be075faa05ea980e5240739c69101a4ba/.taskcluster.yml#L217

```YML
- $if: 'tasks_for in ["github-pull-request"]'
                                      then:
                                          MOBILE_PULL_REQUEST_NUMBER: '${event.pull_request.number}'
```

Example PR task:  https://firefox-ci-tc.services.mozilla.com/tasks/W1YMP7E5QwOW5pWn4q6zkQ and `task.payload.env`

```JSON
"payload": {
    "env": {
      "VCS_PATH": "/builds/worker/checkouts/vcs",
      "REPOSITORIES": "{\"mobile\": \"Focus-Android\"}",
      "HG_STORE_PATH": "/builds/worker/checkouts/hg-store",
      "MOZ_SCM_LEVEL": "1",
      "GOOGLE_PROJECT": "moz-focus-android",
      "MOZ_AUTOMATION": "1",
      "MOBILE_HEAD_REF": "6478",
      "MOBILE_HEAD_REV": "3650e94e6f93ef8c56932771424fd7b97b51878a",
      "SCCACHE_DISABLE": "1",
      "MOBILE_BASE_REPOSITORY": "https://github.com/mozilla-mobile/focus-android",
      "MOBILE_HEAD_REPOSITORY": "https://github.com/iorgamgabriel/focus-android",
      "MOBILE_REPOSITORY_TYPE": "git",
      "GOOGLE_APPLICATION_CREDENTIALS": ".firebase_token.json"
    }
```

This works on the Fenix repository. There must be a conditional difference affecting this?
